name: graphes

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Installation de graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Lancement graphviz
        run: ./NOM-SCRIPT.sh g1

      - name: Upload du résultat
        uses: actions/upload-artifact@v4
        with:
          name: resultat-graphviz
          path: chemin/vers/le/fichier

