name: graphes
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installation de graphviz
      run: sudo ...
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Lancement graphviz
      run: ./NOM-SCRIPT.sh g1
    - name: upload du resultat
      uses: actions/upload-artifact@v4
      with:
        name: (donner un nom arbitraire)
        path: chemin/vers/le/fichier
